server:
  port: 8080
  servlet:
    context-path: /competition


spring:
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, classpath:/templates/
  mvc:
    #    当前文件夹下的所有文件都视为静态文件，里面的html代码才能被浏览器访问到
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/competition_system?serverTimezone=UTC&useSSL=false&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  typeAliasesPackage: com.zln.competition.bean
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    com.zln.competition.mapper: debug